name: Apply testing JS redirect

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  js-redirect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepend JS redirect into /var/www/html/index.html
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TEST_HOST }}
          username: ${{ secrets.TEST_USERNAME }}
          key: ${{ secrets.TEST_SSH_KEY }}
          port: ${{ secrets.TEST_SSH_PORT }}
          script_stop: true
          script: |
            set -euo pipefail

            INDEX=/var/www/html/index.html
            if [ ! -f "$INDEX" ]; then
              echo "❌ $INDEX not found"
              exit 1
            fi

            if sudo grep -q 'data-id="TestingHostRedirect"' "$INDEX"; then
              echo "✅ JS redirect already present; skipping"
              exit 0
            fi

            echo "==> Backing up index.html"
            sudo cp "$INDEX" "$INDEX.bak.$(date +%s)"

            echo "==> Writing injection script"
            sudo bash -lc 'cat > /tmp/inject_testing_redirect.js <<"EOF"\n<script data-id="TestingHostRedirect">(function(h){if(h==="testing.exight.in"){window.location.replace("https://rescuedragon.github.io/exight2.0/");}})(window.location.hostname);</script>\nEOF'

            echo "==> Prepending JS to index.html"
            sudo bash -lc 'cat /tmp/inject_testing_redirect.js "$INDEX" > /tmp/index.new && mv /tmp/index.new "$INDEX"'

            echo "==> Showing first 30 lines"
            sudo sed -n '1,30p' "$INDEX"


