name: Apply testing redirect

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  redirect-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH into testing server and apply Apache redirect
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TEST_HOST }}
          username: ${{ secrets.TEST_USERNAME }}
          key: ${{ secrets.TEST_SSH_KEY }}
          port: ${{ secrets.TEST_SSH_PORT }}
          script_stop: true
          script: |
            set -euo pipefail

            echo "==> Creating redirect config for testing.exight.in"
            sudo tee /etc/httpd/conf.d/redirect-testing.conf >/dev/null <<'EOF'
            # Auto-managed by GitHub Actions: Redirect testing.exight.in to GitHub Pages
            # Applies at server context using mod_rewrite and restricts by Host header
            <IfModule mod_rewrite.c>
              RewriteEngine On
              RewriteCond %{HTTP_HOST} ^testing\.exight\.in$ [NC]
              RewriteRule ^/(.*)$ https://rescuedragon.github.io/exight2.0/$1 [R=301,L]
            </IfModule>
            EOF

            echo "==> Checking loaded modules for mod_rewrite"
            sudo apachectl -M | grep -i rewrite || echo "mod_rewrite not listed; continuing"

            echo "==> Validate Apache configuration"
            sudo apachectl configtest

            echo "==> Reload Apache"
            sudo systemctl reload httpd || sudo service httpd reload

            echo "==> Post-check: fetch headers"
            curl -I -L -s https://testing.exight.in | sed -n '1,20p'


