name: Apply testing JS redirect

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  js-redirect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject meta refresh redirect into /var/www/html/index.html
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TEST_HOST }}
          username: ${{ secrets.TEST_USERNAME }}
          key: ${{ secrets.TEST_SSH_KEY }}
          port: ${{ secrets.TEST_SSH_PORT }}
          script_stop: true
          script: |
            set -euo pipefail

            INDEX=/var/www/html/index.html
            if [ ! -f "$INDEX" ]; then
              echo "❌ $INDEX not found"
              exit 1
            fi

            if sudo grep -q 'http-equiv="refresh"' "$INDEX"; then
              echo "✅ Meta refresh already present; skipping"
              exit 0
            fi

            echo "==> Backing up index.html"
            sudo cp "$INDEX" "$INDEX.bak.$(date +%s)"

            echo "==> Inserting meta refresh after <head> tag"
            sudo sed -i '0,/<head>/s//&\n    <meta http-equiv="refresh" content="0; url=https:\/\/rescuedragon.github.io\/exight2.0\/">/' "$INDEX"

            echo "==> Showing first 30 lines"
            sudo sed -n '1,30p' "$INDEX"


